language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

install: make install
script:
  - make test
  - if [[ $TRAVIS_PHP_VERSION = "7.3" || $TRAVIS_PHP_VERSION = "nightly" ]]; then true; else make check-style; fi
